
http_server_listen: ":4274"

no_pin_code_impl: ['qqRegisterCaptcha',
                   'qqPwdLoginCaptcha',
                   'winQQ_551_sign',
                   'winQQ_554_sign',
                   'qq9065RpcGroup',
                   'qq9120RpcGroup',
]

pin_code_impl: ['qqRegisterCheckOrSendSms']
